import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    loEvent: 'src/loEvent.ts',
    queue: 'src/queue.ts',
    debugLog: 'src/debugLog.ts',
    consoleLogger: 'src/consoleLogger.ts',
    nullLogger: 'src/nullLogger.ts',
    websocketLogger: 'src/websocketLogger.ts',
    reduxLogger: 'src/reduxLogger.ts',
    browserEvents: 'src/browserEvents.ts',
    browserStorage: 'src/browserStorage.ts',
    disabler: 'src/disabler.ts',
    util: 'src/util.ts',
    memoryQueue: 'src/memoryQueue.ts',
    indexeddbQueue: 'src/indexeddbQueue.ts',
    types: 'src/types.ts',
    'metadata/browserinfo': 'src/metadata/browserinfo.ts',
    'metadata/chromeauth': 'src/metadata/chromeauth.ts',
    'metadata/storage': 'src/metadata/storage.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  target: 'es2022',
  external: ['ws', 'redux', 'redux-thunk', 'redux-state-sync', 'lodash'],
});
